acme_blog:
    resource: "@AcmeBlogBundle/Controller/"
    type:     annotation
    prefix:   /

acme_blog_rest:
    type: rest
    prefix: /api
    resource: "@AcmeApiBundle/Resources/config/routes.yml"

